// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Persist the selected harness to config. `harness == None` selects native.
 */
export type InterpreterHarnessSetParams = {
/**
 * Harness id, e.g. `"claude-code"`; `None` selects the native harness.
 */
harness?: string | null,
/**
 * Optional config profile to write to instead of the top level.
 */
profile?: string | null, };
