// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * List the harness choices compatible with a provider/model.
 */
export type InterpreterHarnessListParams = { providerId: string,
/**
 * Optional model; refines the compatible harness set.
 */
model?: string | null, };
