// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReasoningEffort } from "../ReasoningEffort";

/**
 * Persist the selected model (and optional reasoning effort) to config.
 */
export type InterpreterModelSetParams = { model: string, reasoningEffort?: ReasoningEffort | null,
/**
 * Optional config profile to write to instead of the top level.
 */
profile?: string | null, };
