// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InterpreterProviderKind } from "./InterpreterProviderKind";
import type { ProviderReadinessDto } from "./ProviderReadinessDto";
import type { WireApiDto } from "./WireApiDto";

/**
 * One provider entry for the `/model` picker, mirroring the TUI's
 * `ProviderChoice`. The list is the union of configured providers and
 * quick-add presets, with the OpenAI ChatGPT-vs-API-key split and readiness
 * sort already applied by the server.
 *
 * `description` is the picker subtitle (already decorated with the readiness
 * suffix and any "| Harness: <name>" hint). `readiness` is the raw label.
 * `is_current` marks the active provider; `starts_new_chat` is true when
 * selecting this entry begins a new chat (i.e. it is not the current
 * provider). `kind` distinguishes already-configured entries from quick-add
 * presets. `configured` is true exactly when `kind == Existing`; `is_default`
 * is true when `id` equals `config.model_provider_id`. `base_url`, `wire_api`,
 * and `env_key` are present for configured providers and may be absent for
 * presets.
 */
export type InterpreterProvider = { id: string, name: string, description: string, readiness: ProviderReadinessDto, kind: InterpreterProviderKind, isCurrent: boolean, startsNewChat: boolean, baseUrl?: string, wireApi?: WireApiDto, envKey?: string, configured: boolean, isDefault: boolean, };
