// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A harness choice for a provider/model. `id == None` is the native (Codex)
 * harness.
 */
export type InterpreterHarness = {
/**
 * e.g. `"claude-code"`, `"kimi-cli"`; `None` means the native harness.
 */
id?: string,
/**
 * Human-facing label, e.g. `"Claude Code (recommended)"`.
 */
label: string, description: string, isRecommended: boolean, };
