// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * List models for a provider.
 */
export type InterpreterModelListParams = {
/**
 * Optional provider override; defaults to the active provider.
 */
modelProvider?: string | null,
/**
 * When true, include models hidden from the default picker list.
 */
includeHidden?: boolean | null, };
