// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Persist the selected provider to config (affects future turns).
 */
export type InterpreterProviderSetParams = { providerId: string,
/**
 * Optional config profile to write to instead of the top level.
 */
profile?: string | null,
/**
 * API key for a quick-add preset that requires one and has no matching
 * environment variable set. Ignored for already-configured providers.
 */
apiKey?: string | null, };
