// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Readiness label for a provider entry, mirroring the TUI `/model` picker.
 * Drives the trailing decoration on `description` (e.g. "· Logged in").
 */
export type ProviderReadinessDto = "loggedIn" | "ready" | "installed" | "needsSetup";
