// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Wire protocol a provider speaks, as it appears on the app-server JSON-RPC/TS
 * contract. Deliberately a standalone copy of `codex_model_provider_info::WireApi`,
 * which lives in a heavy domain crate this protocol crate must not depend on; a
 * dedicated wire type also keeps the generated bindings insulated from internal
 * refactors of that enum. Converters map between the two with an exhaustive match,
 * so a new variant on either side fails to compile until it is mapped.
 */
export type WireApiDto = "responses" | "chat" | "messages";
