// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a model's reasoning behavior can be controlled by the client UI/API.
 */
export type ReasoningControl = "none" | "fixed" | "effort" | "thinking_toggle" | "thinking_budget";
